package com.neusoft.ehr.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of hr_menus.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class HrMenus implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Long id;

	/** url. */
	private String url;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	private String name;
	public HrMenus() {

	}

	public HrMenus(Long id, String url,String name ) {
		this.name=name;
		this.id = id;
		this.url = url;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
}
