package com.neusoft.ehr.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of hr_roles.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class HrRoles implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Long id;

	/** role_name. */
	private String roleName;

	/** role_code. */
	private Integer roleCode;

	public HrRoles() {
	}

	public HrRoles(Long id, String roleName, Integer roleCode) {
		this.id = id;
		this.roleName = roleName;
		this.roleCode = roleCode;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Integer getRoleCode() {
		return roleCode;
	}

	public void setRoleCode(Integer roleCode) {
		this.roleCode = roleCode;
	}
}
