package com.neusoft.ehr.entity;

import java.io.Serializable;

/**
 * Model class of hr_roles_menus.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class HrRolesMenus implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** hr_roles. */
	private HrRoles roleHrRoles;

	/** hr_menus. */
	private HrMenus menuHrMenus;

	/**
	 * Constructor.
	 */
	public HrRolesMenus() {
	}

	public HrRolesMenus(HrRoles roleHrRoles, HrMenus menuHrMenus) {
		this.roleHrRoles = roleHrRoles;
		this.menuHrMenus = menuHrMenus;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public HrRoles getRoleHrRoles() {
		return roleHrRoles;
	}

	public void setRoleHrRoles(HrRoles roleHrRoles) {
		this.roleHrRoles = roleHrRoles;
	}

	public HrMenus getMenuHrMenus() {
		return menuHrMenus;
	}

	public void setMenuHrMenus(HrMenus menuHrMenus) {
		this.menuHrMenus = menuHrMenus;
	}
}
