package com.neusoft.ehr.entity;

import java.io.Serializable;

/**
 * Model class of hr_users_roles.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class HrUsersRoles implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** hr_roles. */
	private HrRoles roleHrRoles;

	/** hr_users. */
	private HrUsers userHrUsers;

	/**
	 * Constructor.
	 */
	public HrUsersRoles() {
	}

	public HrUsersRoles(HrRoles roleHrRoles, HrUsers userHrUsers) {
		this.roleHrRoles = roleHrRoles;
		this.userHrUsers = userHrUsers;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public HrRoles getRoleHrRoles() {
		return roleHrRoles;
	}

	public void setRoleHrRoles(HrRoles roleHrRoles) {
		this.roleHrRoles = roleHrRoles;
	}

	public HrUsers getUserHrUsers() {
		return userHrUsers;
	}

	public void setUserHrUsers(HrUsers userHrUsers) {
		this.userHrUsers = userHrUsers;
	}
}
