package com.neusoft.ehr.entity;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of hr_users.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class HrUsers implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Long id;

	/** username. */
	private String username;

	/** last_login_time. */
	private Timestamp lastLoginTime;

	/** last_leave_time. */
	private Timestamp lastLeaveTime;

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	private String password;
	public HrUsers() {
	}

	public HrUsers(String username,String password){
		this.password = password;
		this.username = username;
	}
	public HrUsers(Long id, String username, Timestamp lastLoginTime, Timestamp lastLeaveTime,String password) {
		this.id = id;
		this.username = username;
		this.lastLoginTime = lastLoginTime;
		this.lastLeaveTime = lastLeaveTime;
		this.password = password;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Timestamp getLastLoginTime() {
		return lastLoginTime;
	}

	public void setLastLoginTime(Timestamp lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public Timestamp getLastLeaveTime() {
		return lastLeaveTime;
	}

	public void setLastLeaveTime(Timestamp lastLeaveTime) {
		this.lastLeaveTime = lastLeaveTime;
	}
}
